Repository puppetlabs/provision, pull requests merged in 2020-11, with the labels that each got.

#112 docker: support podman; improve handling of OS distribution/version for non-litmusimage images
  tasks/docker.rb
Labels: feature

#132 Fix amazonlinux detection
  tasks/docker.rb
Labels: bugfix

#133 (IAC-1227) fallback to imagename-based platform calculation for images that don't have `/etc/os-release`
  tasks/docker.rb
Labels: bugfix

#134 (IAC-1229) - Fix for Docker Oracle Linux
  tasks/docker.rb
Labels: bugfix

#135 (maint) - Fix for Docker Oracle Linux 6
  tasks/docker.rb
Labels: bugfix

#136 (MAINT) Update Docker provisioner image name gsub with '.'
  tasks/docker.rb
Labels: bugfix

#139 pdksync - Update pdk-templates for gitpod and codespaces support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitpod.Dockerfile
  .gitpod.yml
  .pdkignore
  .rubocop.yml
  .sync.yml
  data/common.yaml
  hiera.yaml
  metadata.json
Labels: maintenance

#140 misc provision_service improvements
  tasks/provision_service.rb
Labels: bugfix

#141 Add target_names to bolt response for connectivity check
  tasks/provision_service.rb
Labels: feature
