Repository puppetlabs/provision, pull requests merged in 2020-02, with the labels that each got.

#93 (feat) move to v2 of the bolt inventory file
  lib/task_helper.rb
  tasks/abs.rb
  tasks/docker.rb
  tasks/docker_exp.rb
  tasks/vagrant.rb
  tasks/vmpooler.rb
Labels: backwards-incompatible, feature

#96 Add vars support to the docker provisioner
  tasks/docker.json
  tasks/docker.rb
Labels: feature

#97 Add explicit failure on .fog file failure
  lib/task_helper.rb
Labels: maintenance

#101 Fix vagrant provisioner to run with spaces in arguments
  .gitignore
  tasks/vagrant.rb
Labels: bugfix

#104 (MAINT) Fix vagrant provision on Windows
  tasks/vagrant.rb
Labels: bugfix

#107 (bugfix) change the server url for pe
  tasks/install_pe.sh
Labels: bugfix
