Repository puppetlabs/provision, pull requests merged in 2020-05, with the labels that each got.

#114 pdksync - (maint) - Pdk Update
  .gitignore
  .rubocop.yml
  .travis.yml
  .vscode/extensions.json
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#115 Allow abs provider task to get token from fog file and set priority
  lib/task_helper.rb
  tasks/abs.rb
Labels: feature

#116 (IAC-822) Improve robustness of ABS API retry loop
  tasks/abs.rb
Labels: bugfix

#117 (maint) Tune timeout loop in ABS provisioner to increase speed
  tasks/abs.rb
Labels: maintenance
