Repository puppetlabs/provision, pull requests merged in 2020-12, with the labels that each got.

#144 (maint) Fix Rubocop violations for target Ruby version of 2.4
  .rubocop.yml
  lib/task_helper.rb
  metadata.json
  spec/unit/task_helper_spec.rb
  tasks/abs.rb
  tasks/docker.rb
  tasks/docker_exp.rb
  tasks/provision_service.rb
  tasks/run_tests.rb
  tasks/update_node_pp.rb
  tasks/update_site_pp.rb
  tasks/vagrant.rb
  tasks/vmpooler.rb
Labels: maintenance

#143 (feat) Allow for passing docker runtime options
  README.md
  tasks/docker.rb
Labels: feature

#145 Add propagating the honeycomb trace context to the provision calls
  tasks/provision_service.rb
Labels: feature

#150 Fix typo from rubocop fixes in docker provisioner
  tasks/docker.rb
Labels: bugfix

#146 (feat) allow abs to provision multiple of machines
  tasks/abs.json
  tasks/abs.rb
Labels: feature
