Repository puppetlabs/provision, pull requests merged in 2021-04, with the labels that each got.

#163 new install_puppetserver.sh task
  tasks/install_puppetserver.json
  tasks/install_puppetserver.sh
Labels: feature

#164 (maint) Removing vmpooler
  README.md
  lib/task_helper.rb
  plans/provisioner.pp
  plans/teardown.pp
  tasks/vmpooler.json
  tasks/vmpooler.rb
Labels: maintenance

#161 (GH-380) Moving inventory.yaml to /spec/fixtures/litmus_inventory.yaml
  tasks/abs.rb
  tasks/docker.rb
  tasks/docker_exp.rb
  tasks/provision_service.rb
  tasks/vagrant.rb
Labels: bugfix

#165 pdksync - (maint) Running pdk update
  .gitignore
  .gitpod.yml
  .pdkignore
  .rubocop.yml
  .travis.yml
  metadata.json
  spec/spec_helper.rb
Labels: maintenance
