Repository puppetlabs/provision, pull requests merged in 2023-07, with the labels that each got.

#221 (CONT-1241) - Retrying when response body is nil or empty but response code is 200
  .rubocop_todo.yml
  spec/tasks/abs_spec.rb
  spec/tasks/provision_service_spec.rb
  tasks/provision_service.rb
Labels: maintenance

#223 (MAINT) Updating release workflows with reusable workflows
  .changelog.yml
  .github/workflows/release_prep.yml
  CHANGELOG.md
Labels: maintenance

#226 (CAT-1211) - Fixing regression of CAT-1241
  .changelog.yml
  tasks/provision_service.rb
Labels: maintenance

#228 (CAT-1253) - Fixes undefined variable in vagrant provisioner
  tasks/vagrant.rb
Labels: bugfix

#229 (maint) - add version input to release_prep
  .github/workflows/release_prep.yml
Labels: maintenance

#231 (CAT-1264) - Drop Support for EOL Windows 2008 R2, Debian 8 + Ubuntu 16.04
  metadata.json
Labels: backwards-incompatible

#232 (CAT-1264) - Add Support for CentOS 8, RHEL 8/9, Debian 10/11, Ubuntu 18/20/22, Windows 16/19/22
  metadata.json
Labels: feature

#233 (maint) - Update to use module ci
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: maintenance

#234 (maint) - Update README
  README.md
Labels: maintenance
