Repository puppetlabs/provision, pull requests merged in 2023-05, with the labels that each got.

#209 Fixed: tasks/docker.rb
  tasks/docker.rb
Labels: bugfix, community

#210 (CONT-953) Fix bad include method
  tasks/docker_exp.rb
Labels: bugfix

#211 (CONT-954) Pin changelog generator to 1.15.2
  .sync.yml
  Gemfile
  Rakefile
Labels: maintenance

#214 Fix release workflow
  .github/workflows/release.yml
Labels: maintenance

#205 (CONT-809) Add Puppet 8 support
  .fixtures.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .rubocop.yml
  .rubocop_todo.yml
  lib/task_helper.rb
  metadata.json
  spec/spec_helper.rb
  spec/tasks/abs_spec.rb
  spec/unit/task_helper_spec.rb
  tasks/abs.rb
  tasks/docker.rb
  tasks/docker_exp.rb
  tasks/provision_service.rb
  tasks/run_tests.rb
  tasks/update_node_pp.rb
  tasks/update_site_pp.rb
  tasks/vagrant.rb
Labels: backwards-incompatible

#216 (maint) - Add connect-timeout to transport
  tasks/abs.rb
  tasks/docker.rb
  tasks/docker_exp.rb
  tasks/vagrant.rb
Labels: enhancement, MayTheSourceBeWithYou

#217 (CONT-930) - Roll out new changelog generator
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
Labels: maintenance
