Repository puppetlabs/provision, pull requests merged in 2024-05, with the labels that each got.

#261 fix provision on dnf only platforms
  tasks/docker.rb
Labels: bugfix

#264 (CAT-372) - add var support to vagrant provisioner
  README.md
  spec/tasks/vagrant_spec.rb
  tasks/vagrant.json
  tasks/vagrant.rb
Labels: feature

#265 (IT-87329) - Update workflows to run on pull_request
  .github/workflows/mend.yml
Labels: maintenance

#251 LXD provisoner support
  lib/task_helper.rb
  spec/tasks/lxd_spec.rb
  tasks/lxd.json
  tasks/lxd.rb
Labels: feature
