Repository puppetlabs/provision, pull requests merged in 2024-07, with the labels that each got.

#259 tasks require path to inventory yaml
  .github/workflows/ci.yml
  README.md
  lib/task_helper.rb
  plans/provisioner.pp
  plans/teardown.pp
  spec/tasks/abs_spec.rb
  spec/tasks/vagrant_spec.rb
  tasks/abs.rb
  tasks/docker.rb
  tasks/docker_exp.rb
  tasks/lxd.rb
  tasks/provision_service.rb
  tasks/vagrant.rb
Labels: feature

#260 Uncouple from the puppet_litmus gem
  README.md
  lib/docker_helper.rb
  lib/inventory_helper.rb
  lib/task_helper.rb
  spec/spec_helper_local.rb
  spec/tasks/abs_spec.rb
  spec/tasks/lxd_spec.rb
  spec/tasks/provision_service_spec.rb
  spec/tasks/vagrant_spec.rb
  spec/unit/docker_helper_spec.rb
  spec/unit/inventory_helper_spec.rb
  tasks/abs.json
  tasks/abs.rb
  tasks/docker.json
  tasks/docker.rb
  tasks/docker_exp.json
  tasks/docker_exp.rb
  tasks/lxd.json
  tasks/lxd.rb
  tasks/provision_service.json
  tasks/provision_service.rb
  tasks/vagrant.json
  tasks/vagrant.rb
Labels: feature

#268 fix tear_down from puppet_litmus
  tasks/docker.rb
  tasks/docker_exp.rb
  tasks/provision_service.rb
  tasks/vagrant.rb
Labels: bugfix, community

#269 pdksync - (CAT-1954) Remove labeller
  .github/workflows/labeller.yml
Labels: maintenance

#270 (CAT-1958) - Fix 404 on teardown of abs node
  tasks/abs.rb
Labels: bugfix
